version: "3.7"
services:
  nginx:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - ${APP_PATH}:/var/www/html
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d:ro
      - ${NGINX_CERT_PATH}:/etc/nginx/certs
      - ${NGINX_LOGS_PATH}:/var/log/nginx

